### ISSUE TITLE
return feed without sorting by time

### ISSUE THREAD

**Issue by aviaryan** [iiitv/hackathon-fullstack-server#2]
Again this is a measure to save time and have a working prototype sooner.

**Comment by singhpratyush** [comment]
This will do. Sorting at client side is easy and fast.

**Comment by aviaryan** [comment]
@singh-pratyush96 Will you able to parse date from string formats like - 

```
Sat, 12 Mar 2016 18:11:44 +0100
2015-12-27 07:38:54 GMT
```

**Comment by singhpratyush** [comment]
Will have to do some parsing.

`YYYY-MM-DD HH:MM:SS` is supported by SQLite.

**Comment by aviaryan** [comment]
@singh-pratyush96 You don't need to parse now. The server now always returns time in `YYYY-MM-DD HH:MM:SS` format.  see #4
